# Site settings
title: Lucas H. Ueda
description: |
  Lucas H. Ueda is an speech synthesis researcher based on Brazil.

url: lucashueda.github.io

about_title: About
posts_title: Posts
projects_title: Projects
publications_title: Publications

# User settings
user_description_appendix: |
  I created this website to store my thoughts and share my personal projects, mostly, on AI. My research topics are:
  artificial intelligence, gen ai, speech synthesis, voice conversion, representation learning and affective computing.

  This website was built on top of [Rassaby][rassaby] template all credits to him.
  
  [rassaby]: https://github.com/lrassaby/lrassaby.github.io

email: lucashueda@gmail.com
linkedin: lucashueda
github: lucashueda
scholar: BF91_LQAAAAJ&hl=pt-BR
#angellist: rassaby

relevant_tags: ['projects', 'tutorials', 'blog']

resume_url: assets/files/Resume_Lucas_Ueda_20240925.pdf
# music_resume_url: https://docs.google.com/document/d/17F3g8jx2UHby77P7shJlsKAW2Efasuc1HuQ3Ro3v3zI/export?format=pdf

author: Lucas H. Ueda
author_title: Speech Researcher
author_photo: profile.jpeg
user_description_short: |
  I'm a PhD student and a Speech Researcher with focus on speech synthesis.


## Disqus
disqus_identifier: lucashueda

## Tracker
google_analytics_id: UA-109461282-1

keywords: 'python, ai, deep learning, data science, speech synthesis, tts, voice conversion, vc'

## URLs
permalink: ':title/'

baseurl: ''
posts_url: '/'
about_url: '/about'
publications_url: '/publications'
projects_url: '/projects'


plugins:
  - jekyll-feed


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']